name: xnlivescore
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  provider: ^3.1.0
  overlay_support: ^1.0.2
  url_launcher: ^5.4.2
  firebase_auth: ^0.14.0+5
  cloud_firestore: ^0.12.9+5
  google_sign_in: ^4.4.1
  firebase_core: ^0.4.4+3
  rxdart: ^0.23.1
  flutter_spinkit: "^4.1.2"
  flutter_line_sdk:
  firebase_database: ^3.1.5
  flutter_svg: any
  firebase_remote_config: ^0.2.0+7
  logger: ^0.7.0+2
  redux_persist_flutter: ^0.8.2
  intl: ^0.16.1
  webview_flutter: ^0.3.22+1
  shared_preferences: ^0.5.3+4
  http: ^0.12.1


dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/facebook.png
    - assets/line.png
    - assets/appfinal.png
    - assets/images/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/Montserrat-Regular.ttf
        - asset: assets/Montserrat-Bold.ttf
          weight: 700